"""Add emotion_profile column to book table

Revision ID: 774e91b2ce14
Revises: fca3cd9a74e7
Create Date: 2026-03-20 19:44:39.657326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774e91b2ce14'
down_revision: Union[str, None] = 'fca3cd9a74e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion_profile', sa.String(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_id',
                existing_type=sa.NUMERIC(),
                type_=sa.String(),
                existing_nullable=False)
        batch_op.alter_column('user_id',
                existing_type=sa.NUMERIC(),
                type_=sa.String(),
                existing_nullable=False)
        batch_op.alter_column('book_id',
                existing_type=sa.NUMERIC(),
                type_=sa.String(),
                existing_nullable=False)
        batch_op.drop_constraint('fk_reviews_book_id_book', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_book_id_book', 'book', ['book_id'], ['book_id'])
        batch_op.create_foreign_key('fk_reviews_user_id_user', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'book', ['book_id'], ['book_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('reviews', 'book_id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reviews', 'review_id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('book', 'emotion_profile')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=1)
    # ### end Alembic commands ###
